



import React, { useState, useRef, useEffect } from "react";
import AnimatedText from '../components/AnimatedText'
import styles from '../styles/Home.module.css'
import styleslayout from '../styles/layout.module.css'
import Head from 'next/head'
import Image from 'next/image'
import logo from '../styles/logo.module.css'

import "react-responsive-carousel/lib/styles/carousel.min.css"; 

import profilePic from "../../public/images/profile/developer-pic-1.png";
import profil from "../../public/images/profile/profil.jpg";
import profil2 from "../../public/images/profile/woman.png";
import profil3 from "../../public/images/profile/woman2.png";
import Call from '../components/Call';

import SuperimposedCarousel from "../components/SuperimposedCaroussel";

import Logo from "../components/Logo";
import Transitioneffect from "../components/Transitioneffect";


export default function Home({Modedark}) {

 

 
  const [HeureOuvert, setHeureOuvert] = useState(false);
  
   useEffect(() => {
    // Obtenez l'heure actuelle
    const maintenant = new Date();
    const heureActuelle = maintenant.getHours();
  
      
  
    // Vérifiez si l'heure actuelle est entre 9h00 et 18h00
    const estHeureOuvert = heureActuelle >= 9 && heureActuelle < 18;

    // Mettez à jour l'état en conséquence
    setHeureOuvert(estHeureOuvert);
  }, [])
  const votreTableauDImages = [
    "https://1.bp.blogspot.com/-_XJwUQpH-OY/XWk9kieT56I/AAAAAAAAJOM/8ArKNPq8OjgC4ht3J1pM9DvzqsspuIUkACLcBGAs/s1600/Bank%2BMandiri%2B%255Bwww.blogovector.com%255D.png",
    "https://revistablogurilor.ro/wp-content/uploads/2015/12/banca.jpg",
    "https://www.wavestone.com/app/uploads/2022/03/Featured-client-story-BNP.png",
    // Ajoutez d'autres chemins d'accès aux images ici
  ];

  const votreTableauDImagescommentaire = [
    "https://1.bp.blogspot.com/-_XJwUQpH-OY/XWk9kieT56I/AAAAAAAAJOM/8ArKNPq8OjgC4ht3J1pM9DvzqsspuIUkACLcBGAs/s1600/Bank%2BMandiri%2B%255Bwww.blogovector.com%255D.png",
    "https://revistablogurilor.ro/wp-content/uploads/2015/12/banca.jpg",
    "https://www.wavestone.com/app/uploads/2022/03/Featured-client-story-BNP.png",
    // Ajoutez d'autres chemins d'accès aux images ici
  ];
  
  const votreTableauText = [
   "Text1",
   "Text2",
   "Text3",
  
  ];


  return (
    <>
      <Head>
      <title>Mon courtier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <Transitioneffect />
      <main className= {styleslayout.imageindex }>
        <section className={Modedark === "dark" ? styleslayout.mainmodedark  :  styleslayout.main }>

 
        <Logo text="Laurent Doenil" className={`${logo.prenom}` } lien="/about"/>

        <div className={styleslayout.description2}>

  





<span >
  
<AnimatedText
  className={styleslayout.cardbouton}
  text="Un DESSEIN ?"
  text2="Un PROFIT ?"
  text3="Un PROJET ?"
  text4="06.08.06.08.06"
/>
</span>


</div>
<div className={styleslayout.carte2}>




        </div>
 <div className={styleslayout.bureau}>
      {HeureOuvert ? (
        <p><span className={styleslayout.ouvert}>OUVERT</span>  <span className={styleslayout.horaires} >Horaires : Lundi au Samedi 9h00-18h00 </span></p>
      ) : (
        <p><span className={styleslayout.ferme}>FERME</span> <span className={styleslayout.horaires} >Horaires : Lundi au Samedi 9h00-18h00 </span></p>
      )}
    </div>
        <div >
        <Image src={profilePic} alt="courtier" />
        <Logo   text="Courtier en Assurances Champigny-sur-Marne" className= {HeureOuvert ? (
       `${logo.descr}`
      ) : (
        `${logo.descr2}`
      )} lien="/about"/>
        </div>
         
   
      
      
        
        <Call className ={styleslayout.call}/>
   
   
       
       
       
       
       
  
   
 <div className={styleslayout.caroussel}>
  

<SuperimposedCarousel images={votreTableauDImages}/>
</div>

</section>  

        <div className={styleslayout.description}>


<div className={styleslayout.divclass}>
 <span className={styleslayout.decalage}></span>


<span className={styleslayout.spanclass}>
<a href="http://google.fr" target="_blank" className={styleslayout.textdeco}>
<AnimatedText
  className={styles.card}
  text="Une REALITE"
  text2="Un PROFIT"
  text3="Un PROJET"
  text4="Contactez-moi"
/>
</a>
</span>


</div>

        </div>

       

       
     
        <div  className={Modedark === "dark" ? styleslayout.caroussel2dark  : styleslayout.caroussel2 }>

{/*  <SuperimposedCarouselText images={votreTableauDImagescommentaire} text={votreTableauText} /> */}
 
{/* <SwiperOK posts={yourData}/> */}
<div>
  <div className={styleslayout.images}>

  <Image src={profil} alt="courtier"className={styleslayout.image1}/>


  </div>
  
  
  <div className={styleslayout.etoiles}>⭐⭐⭐⭐⭐</div>
<div className={styleslayout.text}>Un bon courtier, très réactif, je recommande. </div>

</div>

<div >  
<div className={styleslayout.images}>

<Image src={profil2} alt="courtier"className={styleslayout.image1}/>


</div>
<div className={styleslayout.etoiles}>⭐⭐⭐⭐⭐</div>
  


<div className={styleslayout.text}>Parfait, merci Laurent... </div></div>

<div>   <div className={styleslayout.images}>

<Image src={profil3} alt="courtier"className={styleslayout.image1}/>


</div> <div className={styleslayout.etoiles}>⭐⭐⭐⭐⭐</div>
<div className={styleslayout.text}>On peut lui faire confiance</div></div>
</div>
     
      </main>

 
 
</>
  )
}
